<a href="https://colab.research.google.com/github/petternds/AluraBook/blob/main/ExemploEPratica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlalchemy

In [2]:
from sqlalchemy import create_engine, MetaData, Table, inspect

In [3]:
engine = create_engine('sqlite:///:memory:')

In [4]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

In [5]:
import pandas as pd

In [6]:
dados = pd.read_csv(url)

In [7]:
dados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [8]:
dados.to_sql('clientes', engine, index=False)

438463

In [10]:
inspector = inspect(engine)

In [11]:
print(inspector.get_table_names())

['clientes']

In [12]:
query = 'UPDATE clientes SET Rendimento_anual="300000" WHERE ID_Cliente="6840104"'
query = sqlalchemy.text(query)
with engine.connect() as conn:
    conn.execute(query)
    conn.commit()

In [16]:
query = 'DELETE FROM clientes WHERE ID_Cliente=5008809'
query = sqlalchemy.text(query)
with engine.connect() as conn:
    conn.execute(query)
    conn.commit()

In [17]:
query = 'INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, \
Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, \
Tem_carro, Moradia) \
VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", 2, 290000, 0, "Casa/apartamento próprio")'
query = sqlalchemy.text(query)
with engine.connect() as conn:
    conn.execute(query)
    conn.commit()

In [19]:
query = 'SELECT ID_Cliente FROM clientes'

In [20]:
pd.read_sql(query, engine)

        ID_Cliente
0          5008804
1          5008805
2          5008806
3          5008808
4          5008810
...            ...
438458     6840222
438459     6841878
438460     6842765
438461     6842885
438462     6850985

[438463 rows x 1 columns]

In [23]:
query = 'SELECT * FROM clientes WHERE ID_cliente=6850985'

In [24]:
pd.read_sql(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6850985,33,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio